import { RulePreset } from '../types';

export const RULE_PRESETS: RulePreset[] = [
  // ─── 1. TIMING RULES ────────────────────────────────────────────────────────
  {
    type: 'max_trades_per_day',
    category: 'timing',
    name: 'Max Trades Per Day Limit',
    defaultValue: '5',
    unit: 'trades/day',
    inputType: 'stepper',
    min: 1,
    max: 30,
    step: 1,
    chips: ['3', '5', '8', '10'],
    severity: 'critical',
    desc: 'Halt trading when reaching this daily limit to eliminate overtrading and mental fatigue.',
  },
  {
    type: 'max_trades_per_hour',
    category: 'timing',
    name: 'Max Trades Per Hour Frequency',
    defaultValue: '3',
    unit: 'trades/hour',
    inputType: 'stepper',
    min: 1,
    max: 15,
    step: 1,
    chips: ['2', '3', '4', '5'],
    severity: 'strict',
    desc: 'Cap executions within any 60-minute window to prevent rapid overactivity and churn.',
  },
  {
    type: 'max_trades_per_30min',
    category: 'timing',
    name: 'Max Trades in 30 Minutes',
    defaultValue: '2',
    unit: 'trades/30m',
    inputType: 'stepper',
    min: 1,
    max: 10,
    step: 1,
    chips: ['1', '2', '3', '4'],
    severity: 'strict',
    desc: 'Detect and prevent impulsive rapid-fire trade clusters inside rolling 30-minute windows.',
  },
  {
    type: 'allowed_sessions',
    category: 'timing',
    name: 'Permitted Trading Sessions',
    defaultValue: 'London, New York',
    unit: 'sessions',
    inputType: 'sessions',
    severity: 'strict',
    desc: 'Only enter trades during approved high-liquidity sessions (London, New York, Asian).',
  },

  // ─── 2. RISK RULES ──────────────────────────────────────────────────────────
  {
    type: 'max_risk',
    category: 'risk',
    name: 'Max Risk Per Trade Cap',
    defaultValue: '1.0',
    unit: '%',
    inputType: 'number',
    min: 0.1,
    max: 10.0,
    step: 0.1,
    chips: ['0.5', '1.0', '1.5', '2.0', '3.0'],
    severity: 'critical',
    desc: 'Hard risk cap: Never risk more than this percentage of account balance on a single position.',
  },
  {
    type: 'max_daily_loss',
    category: 'risk',
    name: 'Max Daily Loss Circuit Breaker',
    defaultValue: '2.0',
    unit: '%',
    inputType: 'number',
    min: 0.5,
    max: 20.0,
    step: 0.5,
    chips: ['1.0', '2.0', '3.0', '4.0', '5.0'],
    severity: 'critical',
    desc: 'If daily realized drawdown reaches this threshold, power down the terminal for the day.',
  },
  {
    type: 'max_lot_size',
    category: 'risk',
    name: 'Maximum Position Lot Size',
    defaultValue: '1.0',
    unit: 'lots',
    inputType: 'number',
    min: 0.01,
    max: 50.0,
    step: 0.1,
    chips: ['0.10', '0.50', '1.00', '2.00', '5.00'],
    severity: 'critical',
    desc: 'Hard ceiling on single-order position volume to prevent inadvertent sizing spikes or revenge bets.',
  },
  {
    type: 'daily_profit_target',
    category: 'risk',
    name: 'Daily Profit Target & Capital Lock',
    defaultValue: '2.0',
    unit: '%',
    inputType: 'number',
    min: 0.5,
    max: 20.0,
    step: 0.5,
    chips: ['1.0', '2.0', '3.0', '5.0'],
    severity: 'strict',
    desc: 'Lock in profits once daily target is achieved to prevent late-session giveback tilt.',
  },
  {
    type: 'stop_loss_required',
    category: 'risk',
    name: 'Mandatory Hard Stop-Loss',
    defaultValue: 'true',
    unit: 'enforced',
    inputType: 'boolean',
    severity: 'critical',
    desc: 'Every order must have a registered protective stop-loss placed upon execution.',
  },

  // ─── 3. BEHAVIOR RULES ──────────────────────────────────────────────────────
  {
    type: 'max_consecutive_losses',
    category: 'behavior',
    name: 'Max Consecutive Loss Limit',
    defaultValue: '3',
    unit: 'losses',
    inputType: 'stepper',
    min: 1,
    max: 10,
    step: 1,
    chips: ['2', '3', '4', '5'],
    severity: 'critical',
    desc: 'Mandatory halt after hitting this streak of consecutive losses before emotional tilt occurs.',
  },
  {
    type: 'cooldown_after_loss',
    category: 'behavior',
    name: 'Mandatory Post-Loss Cooldown',
    defaultValue: '15',
    unit: 'minutes',
    inputType: 'number',
    min: 1,
    max: 240,
    step: 5,
    chips: ['5', '10', '15', '30', '60'],
    severity: 'critical',
    desc: 'Mandatory screen detachment following a realized loss before another order can be entered.',
  },
  {
    type: 'cooldown_after_consecutive_losses',
    category: 'behavior',
    name: 'Losing Streak Cooldown',
    defaultValue: '30',
    unit: 'minutes',
    inputType: 'number',
    min: 5,
    max: 480,
    step: 15,
    chips: ['15', '30', '45', '60', '120'],
    severity: 'critical',
    desc: 'Extended mandatory cool-off after hitting consecutive loss cap before risking further capital.',
  },
  {
    type: 'no_lot_increase_after_loss',
    category: 'behavior',
    name: 'No Lot Sizing Escalation After Loss',
    defaultValue: 'true',
    unit: 'enforced',
    inputType: 'boolean',
    severity: 'critical',
    desc: 'Strictly prohibit increasing lot size following a loss. Eliminates martingale & revenge escalation.',
  },

  // ─── 4. ENTRY DISCIPLINE RULES ──────────────────────────────────────────────
  {
    type: 'min_risk_reward',
    category: 'entry',
    name: 'Minimum Risk/Reward Benchmark',
    defaultValue: '2.0',
    unit: 'ratio',
    inputType: 'ratio',
    min: 1.0,
    max: 10.0,
    step: 0.25,
    chips: ['1.5', '2.0', '2.5', '3.0'],
    severity: 'strict',
    desc: 'Setup must offer at least this reward-to-risk ratio (e.g. 1:2.00) with hard SL and TP before entry.',
  },
  {
    type: 'allowed_symbols',
    category: 'entry',
    name: 'Approved Playbook Instruments',
    defaultValue: 'XAUUSD, EURUSD, GBPUSD',
    unit: 'symbols',
    inputType: 'symbols',
    severity: 'strict',
    desc: 'Restrict order executions strictly to your approved watchlist of mastered instruments.',
  },
  {
    type: 'custom_boolean',
    category: 'entry',
    name: 'Custom Playbook Rule',
    defaultValue: 'true',
    unit: 'boolean',
    inputType: 'boolean',
    severity: 'strict',
    desc: 'Custom entry or exit criterion defined for your specific strategy checklist.',
  },
];
